### ISSUE TITLE
One question about copyMakeBorder 

### ISSUE THREAD

**Issue by Ciong** [nikkatsa7/HOG_Zedboard#1]
Hello author, I changed the human identification (64*128) to car detection(128*128) in the process of simulating the code.
However, during the training process, the image pre-processing copyMakeBorder function is inadvertently added to the pre-processing of feature extraction of positive and negative samples. The subsequent recognition effect can be expected. But after I found this problem, I removed this function and retrained it, and found that the effect was far less than before.
When the value in the copyMakeBorder function is changed during the recognition process, it is found to have a certain influence on the result. Why?
Does the training sample need to be processed by the copyMakeBorder function?

**Comment by nikkatsa7** [comment]
Hello and thanks for the email!

Actually the padding function should only add one black pixel of each size
of the input image during the training and not 8.

We used extra pixels padding in order for the algorithm to detect
pedestrians located on the sides of the input image after it has been
trained.

I'm planning to upload the software only part of this project with the
automated training/test processes. This would give anyone the opportunity
to train the algorithm with any dataset they want.

Are you implementing the algorithm in hardware too?

If you wanted, please let me know how this is going.

Many thanks

Best regards
Katsaros Nikos

**Comment by Tomhariless** [comment]
Hi, I am trying to use the kernel and the roots on the SD card. I get the system booted, but have a problem with the arm login. Could you provide the user name and the password so that I can actually run the system please

**Comment by nikkatsa7** [comment]
Hi! As you can see on this [page](https://medium.com/developments-and-implementations-on-zynq-7000-ap/install-ubuntu-16-04-lts-on-zynq-zc702-using-petalinux-2016-4-e1da902eaff7), you must use the default username is **ubuntu** and the password is **temppwd**.
