### ISSUE TITLE
Webcam Model

### ISSUE THREAD

**Issue by Bahadiirr** [nikkatsa7/HOG_Zedboard#9]
Hi,

Thanks for good project. 

What is webcam model in the project?

**Comment by Bahadiirr** [comment]
Also did you connect your webcam to zedboard via usb otg?

**Comment by nikkatsa7** [comment]
Hello,

The usb camera model used for the project was the Logitech Web Camera C270 HD. It was connected to the OTG port via a micro_usb(male)- usb_A(female) adapter.

Cheers

**Comment by Bahadiirr** [comment]
> Hello,
> 
> The usb camera model used for the project was the Logitech Web Camera C270 HD. It was connected to the OTG port via a micro_usb(male)- usb_A(female) adapter.
> 
> Cheers

Thanks...

**Comment by nikkatsa7** [comment]
No problem :)
